main:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
  defaults:
    route: FD\LogViewer\Controller\IndexController.base

fd_symfony_log_viewer:
  resource: .
  type: fd_symfony_log_viewer
  prefix: /log-viewer
