main:
  path: /
  defaults:
    _controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    template: "@templates/index.html.twig"

fd_symfony_log_viewer:
  resource: .
  type: fd_symfony_log_viewer
  prefix: /logs
